print("hellow, python ")
print("hellow, python ")
print("hellow, python ")
print("hellow, python ")
print("hellow, python ")
print("hellow, python ")
print("hellow, world ")
print("hellow, world ")
print("hellow, world ")
print("hellow, world ")
print("hellow, world ")
print("hellow, world ")
print("hello, world")